### ISSUE TITLE
NULL pointer returned with xml_parse()

### ISSUE THREAD

**Issue by tomgrean** [markusfisch/libxml#2]
Your code has a bug in xml_parse(). the code should change like this:
`-	if (xml_parse_chunk(&st, data) && st.root) {`
`+	if (!xml_parse_chunk(&st, data) && st.root) {`
`    return st.root;`
`	}`
In your README, your example code is wrong, too:
`		if (!(root = xml_parse(`
`				"<hello><world>Hello World</world></hello>")) {`
`			char *s = xml_content_find(root, "hello/world");`
this code will only enter "if" when "root" is NULL.

**Comment by markusfisch** [comment]
You're right, fixed in https://github.com/markusfisch/libxml/commit/879e5e47aa3f94f34a3c95881a1cdc7eea6e9f82
